CREATE TABLE author
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE book
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    author_id    BIGINT                                  NOT NULL,
    publisher_id BIGINT,
    category     VARCHAR(255),
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE book_reviews
(
    book_id    BIGINT NOT NULL,
    reviews_id BIGINT NOT NULL
);

CREATE TABLE publisher
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_publisher PRIMARY KEY (id)
);

CREATE TABLE review
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stars      INTEGER,
    commentary VARCHAR(255),
    book_id    BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

ALTER TABLE author
    ADD CONSTRAINT uc_author_name UNIQUE (name);

ALTER TABLE book_reviews
    ADD CONSTRAINT uc_book_reviews_reviews UNIQUE (reviews_id);

ALTER TABLE book
    ADD CONSTRAINT uc_book_title UNIQUE (title);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (id);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_PUBLISHER FOREIGN KEY (publisher_id) REFERENCES publisher (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE book_reviews
    ADD CONSTRAINT fk_boorev_on_book FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE book_reviews
    ADD CONSTRAINT fk_boorev_on_review FOREIGN KEY (reviews_id) REFERENCES review (id);